---
- name: Converge
  hosts: all
  become_method: su
  vars:
    etcd_cert_server_profile_name: server
    etcd_cert_peer_profile_name: peer
    etcd_cert_client_profile_name: client
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
        state: latest
        update_cache: true
  roles:
    - { role: andrewrothstein.cfssl }
  tasks:
    - name: "Include cloud_labs.etcd_cluster_certificates"
      include_role:
        name: "cloud_labs.etcd_cluster_certificates"
