---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - &default
    name: etcd-cert-instance-01
    hostname: etcd-cert-instance-01
    image: python:3.8-bullseye
    groups:
      - etcd
    pre_build_image: true
  - <<: *default
    name: etcd-cert-instance-02
    hostname: etcd-cert-instance-02
  - <<: *default
    name: etcd-cert-instance-03
    hostname: etcd-cert-instance-03
provisioner:
  name: ansible
  inventory:
    host_vars:
      etcd-cert-instance-01:
        etcd_cert_init_ca_node: true
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
