# generate-peer.yml
---

- name: Copy peer (member) configuration
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: '{{ etcd_cert_dir }}/{{ item }}'
    owner: '{{ etcd_cert_user }}'
    group: '{{ etcd_cert_group }}'
    mode: 0644
  loop:
    - peer.json

- name: Check if peer certificate exists
  ansible.builtin.stat:
    path: "{{ etcd_cert_dir }}/{{ etcd_cert_peer_output_name | default('peer') }}.pem"
  register: peer_cert

- name: Generate peer (member) certificates
  ansible.builtin.shell: |
    cfssl gencert \
        -ca={{ etcd_cert_ca_cert_remote_path | default('ca.pem') }} \
        -ca-key={{ etcd_cert_ca_key_remote_path | default('ca-key.pem') }} \
        -config=ca-config.json \
        -profile={{ etcd_cert_peer_profile_name }} \
        peer.json | cfssljson -bare {{ etcd_cert_peer_output_name }}
  args:
    chdir: "{{ etcd_cert_dir }}"
  when: not peer_cert.stat.exists
