# generate-peer.yml
---

- name: Copy peer (member) configuration
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: '{{ etcd_cert_dir }}/{{ item }}'
    owner: '{{ etcd_cert_user }}'
    group: '{{ etcd_cert_group }}'
    mode: 0644
  loop:
    - peer.json

- name: Generate peer (member) certificates
  ansible.builtin.shell: |
    cfssl gencert \
        -ca={{ etcd_cert_ca_cert_path | default('ca.pem') }} \
        -ca-key={{ etcd_cert_ca_key_path | default('ca-key.pem') }} \
        -config={{ etcd_cert_ca_config_path | default('ca-config.json') }} \
        -profile={{ etcd_cert_peer_profile_name | default('peer') }} \
        peer.json | cfssljson -bare {{ etcd_cert_peer_output_name | default('peer') }}
  args:
    chdir: "{{ etcd_cert_dir }}"
