---

- name: Preflight checks
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: Generate CA certificates
  ansible.builtin.include_tasks:
    file: generate-ca.yml
  when: |
    ( etcd_cert_ca_csr is defined )
    and
    ( etcd_cert_ca_config is defined)

- name: Generate client-to-server (server) certificates
  ansible.builtin.include_tasks:
    file: generate-server.yml

- name: Generate server-to-server (peer/member) certificates
  ansible.builtin.include_tasks:
    file: generate-peer.yml

- name: Generate client certificates
  ansible.builtin.include_tasks:
    file: generate-client.yml
