---

- name: Preflight checks
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: Generate CA certificates
  ansible.builtin.include_tasks:
    file: generate-ca.yml
  when:
    - etcd_cert_ca_cert_remote_path is not defined
    - etcd_cert_ca_key_remote_path is not defined

- name: Generate client certificates
  ansible.builtin.include_tasks:
    file: generate-certs.yml
