# preflight.yml
---

- name: CA checks
  block:
    - name: Check CA configuration
      ansible.builtin.assert:
        that:
          - etcd_cert_ca_key_remote_path is defined
          - etcd_cert_ca_key_remote_path != ""
          - etcd_cert_ca_cert_remote_path is defined
          - etcd_cert_ca_cert_remote_path != ""
        fail_msg: Check CA key and cert path
      when: |
        etcd_cert_ca_cert_remote_path is defined
          or
        etcd_cert_ca_key_remote_path is defined

- name: Check if required profiles are exist
  ansible.builtin.assert:
    that:
      - item.profile_name in etcd_cert_ca_config.signing.profiles
  loop: "{{ etcd_cert_matrix }}"
