---
- name: Converge
  hosts: all
  become_method: su
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  roles:
    - { role: andrewrothstein.cfssl }
  tasks:
    - name: "Include cloud_labs.etcd_cluster_certificates"
      ansible.builtin.include_role:
        name: "cloud_labs.etcd_cluster_certificates"
