---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: etcd-cert-instance-01
    hostname: etcd-cert-instance-01
    image: python:3.8-bullseye
    groups:
      - etcd
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
