---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: etcd-cert-instance-01
    hostname: etcd-cert-instance-01
    image: python:3.8-bullseye
    groups:
      - etcd
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
